
GET http://localhost:4000/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2MzY3Mjk3MTMsImV4cCI6MTYzNjcyOTczMywiYXVkIjoiNjE4ZTE2MmY1Mjc1NDQwM2MzZmYwOTFkIiwiaXNzIjoicGlja3VycGFnZS5jb20ifQ.-7EYUZraipJCsAGuvslW6HzhM90xirTseeV-RzISLUs

###Login route
POST  http://localhost:4000/auth/login
Content-Type: application/json

{
  "email": "reach.rambymail@gmail.com",
  "password": "1234"
}

###Register route
POST  http://localhost:4000/auth/register
Content-Type: application/json

{
  "email": "reach.rambymailaaaaa@gmail.com",
  "password": "1234"
}


###Refresh token route
POST  http://localhost:4000/auth/refresh-token
Content-Type: application/json

{
  "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2MzY3Mjk3MTMsImV4cCI6MTY2ODI4NzMxMywiYXVkIjoiNjE4ZTE2MmY1Mjc1NDQwM2MzZmYwOTFkIiwiaXNzIjoicGlja3VycGFnZS5jb20ifQ.7fnEfk1Lj8NEoWqTZhomF3o7A4Du0yqpAl202-YITtc"
}


###Logout route
DELETE  http://localhost:4000/auth/logout
Content-Type: application/json

{
  "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2MzY3Mjk3NDgsImV4cCI6MTY2ODI4NzM0OCwiYXVkIjoiNjE4ZTE2MmY1Mjc1NDQwM2MzZmYwOTFkIiwiaXNzIjoicGlja3VycGFnZS5jb20ifQ.NzQJBMtaOPq4zOx8O8kUUq-SI7pdekzZor1XYJA8QXI"
}

# 